# Generated by Django 2.2.1 on 2019-05-17 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='game',
            name='region',
            field=models.CharField(choices=[('PAL', 'PAL')], max_length=20),
        ),
        migrations.AlterField(
            model_name='game',
            name='release',
            field=models.CharField(choices=[('1991', '1991'), ('1992', '1992'), ('1993', '1993'), ('1994', '1994'), ('1995', '1995'), ('1996', '1996'), ('1997', '1997'), ('1998', '1998'), ('2017', '2017')], max_length=4),
        ),
    ]
